### PR TITLE
fix scrolling

### PR DESCRIPTION
**Pull request by calebziamba**

### CODE REVIEW

**Review by brandonxia01 — COMMENTED** [review]
Any reason it's not just an `overflow-y-auto` classname added to the body object via tailwind directly?

**Comment by calebziamba** [comment]
Because I couldn't find where the `body` tag is generated from Expo. If you know, I agree that's preferable

**Review by brandonxia01 — APPROVED** [review]
Sorry for the delay.. Yeah I'm not sure where the body. NBD since this looks like a unique case

**Comment by Abidouz** [comment]
Way to go

**Pull request merged**
