### PR TITLE
Handle Chords within the lyric text

### PR DESCRIPTION
**Pull request by brandonxia01**
Add support for chords which are interwoven into the lyric text via square brackets, like this https://github.com/Church-Life-Apps/SongsV2/blob/main/models/TempApiObjects.ts#L42

The logic of this code is potentially a little jank so this will probably get a re-design later down the road.

Example of what this would look like:
Screen Shot 2023-04-15 at 7 47 41 PM

Mobile:
Screen Shot 2023-04-15 at 7 47 41 PM

We can figure out getting chords into the actual lyric data in the database some other day.

This PR contains:
* Lyric utils to handle chord data and rendering
* Update to LyricComponent
* Tests

### CODE REVIEW

**Comment by brandonxia01** [comment]
Looking into chordsheetJS as an alternative... 
In the meantime, this PR is still open for review

**Comment by brotatotes** [comment]
those screenshots look absolutely amazing!

**Comment by brandonxia01** [comment]
I looked into chordsheetJS and I couldn't figure it out. This feature is also dependent on getting chord data actually into the database which will be a lot of work and will need the crowdsourcing process done first. I think this PR is good enough for now, and I wanna work on other stuff.

@Daniel-727 @brotatotes @MiTo0o can you guys review this PR as is?

**Review by brotatotes — APPROVED** [review]
epic

**Pull request merged**
