### PR TITLE
Caleb/dark mode

### PR DESCRIPTION
**Pull request by calebziamba**
image
image
image
image
image
image

### CODE REVIEW

**Review by brandonxia01 — COMMENTED** [review]
Getting an error on this one trying to run it
Screen Shot 2024-10-26 at 10 52 27 PM

**Comment by calebziamba** [comment]
> Getting an error on this one trying to run it Screen Shot 2024-10-26 at 10 52 27 PM

Did you run npm install? I had that same problem until I did some package updates

**Review by brandonxia01 — APPROVED** [review]
This is sweet! Awesome 

Just noticed a minor ui bug on the `/edit` page. I think the background only goes down to `h-screen` 
Screen Shot 2024-10-28 at 12 33 28 AM

**Comment by brandonxia01** [comment]
> > Getting an error on this one trying to run it Screen Shot 2024-10-26 at 10 52 27 PM
> 
> Did you run npm install? I had that same problem until I did some package updates

Yup yeah I didn't npm install. Works now. Thanks

**Pull request merged**
